version: 2
jobs:
  test-node-14:
    docker:
      - image: cimg/node:14.20.1
    steps:
      - checkout
      - restore_cache:
          key: node-modules-14-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: node-modules-14-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm test
  test-node-lts:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          key: node-modules-lts-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: node-modules-lts-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm test
  release:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish --access public

workflows:
  version: 2
  build:
    jobs:
      - test-node-14:
          filters:
            tags:
              only: /.*/
      - test-node-lts:
          filters:
            tags:
              only: /.*/
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - test-node-14
            - test-node-lts
